name: Build and Release Nginx

on:
  push:
    branches:
      - main
  tags:
    - 'v*.*.*' # タグを使ってリリースを作成する場合

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev

      - name: Create installation directory
        run: |
          mkdir -p /home/runner/nginx

      - name: Download Nginx source
        run: |
          curl -O https://nginx.org/download/nginx-1.24.0.tar.gz
          tar -xzvf nginx-1.24.0.tar.gz

      - name: Build Nginx
        run: |
          cd nginx-1.24.0
          ./configure --prefix=/home/runner/nginx
          make
          make install

      - name: Archive Nginx binary
        run: |
          tar -czvf nginx.tar.gz -C /home/runner nginx

      - name: Upload Nginx binary as release artifact
        uses: actions/upload-artifact@v3
        with:
          name: nginx-binary
          path: nginx.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: nginx.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
